In [1]:
import pandas as pd
from index import cot_all

In [2]:
df = cot_all()

Selected: COT Legacy report. Futures only.
Downloaded & Stored the extracted file FUT86_16.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2017
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2018
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2019
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2020
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2021
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2022
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2023
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2024
Downloaded & Stored the extracted file annual.txt in the directory data
Selected: legacy_fut
Loading single year data from: 2025
Downloaded & Stored the extracted file annual.txt in the directory data
data cached in the file legacy_fut.csv under the directory: /home/mod7ex/cot-py/data

> pick the asset you want

In [3]:
ASSET_CODE = '088691'

# df[(df['Open Interest (Other)']!= 0) & (df['CFTC Contract Market Code'] == ASSET_CODE)]

df = df[df['CFTC Contract Market Code'] == ASSET_CODE]

In [4]:
df = df.rename(columns={'As of Date in Form YYYY-MM-DD': 'Date'})

df['Date'] = pd.to_datetime(df['Date'])

df.set_index('Date', inplace=True)

df.sort_index(inplace=True)

df.head()

,Market and Exchange Names,As of Date in Form YYMMDD,CFTC Contract Market Code,CFTC Market Code in Initials,CFTC Region Code,CFTC Commodity Code,Open Interest (All),Noncommercial Positions-Long (All),Noncommercial Positions-Short (All),Noncommercial Positions-Spreading (All),...,Concentration-Gross LT =8 TDR-Long (Other),Concentration-Gross LT =8 TDR-Short(Other),Concentration-Net LT =4 TDR-Long (Other),Concentration-Net LT =4 TDR-Short (Other),Concentration-Net LT =8 TDR-Long (Other),Concentration-Net LT =8 TDR-Short (Other),Contract Units,CFTC Contract Market Code (Quotes),CFTC Market Code in Initials (Quotes),CFTC Commodity Code (Quotes)
Date,,,,,,,,,,,,,,,,,,,,,
1986-01-15,GOLD - COMMODITY EXCHANGE INC.,860115,088691,CMX,1,88,148186,18589,7706,12038,...,83.6,73.6,21.5,17.8,25.4,23.1,(CONTRACTS OF 100 TROY OUNCES),088691,CMX,88
1986-01-31,GOLD - COMMODITY EXCHANGE INC.,860131,088691,CMX,1,88,144149,15364,9303,10088,...,75.7,73.7,21.9,25.7,28.8,30.3,(CONTRACTS OF 100 TROY OUNCES),088691,CMX,88
1986-02-14,GOLD - COMMODITY EXCHANGE INC.,860214,088691,CMX,1,88,139995,5457,12229,10330,...,75.7,77.0,19.6,25.9,26.3,30.1,(CONTRACTS OF 100 TROY OUNCES),088691,CMX,88
1986-02-28,GOLD - COMMODITY EXCHANGE INC.,860228,088691,CMX,1,88,143752,7991,12222,13205,...,76.1,77.6,19.4,26.5,26.0,29.5,(CONTRACTS OF 100 TROY OUNCES),088691,CMX,88
1986-03-14,GOLD - COMMODITY EXCHANGE INC.,860314,088691,CMX,1,88,142868,12637,11015,11390,...,76.8,77.0,20.4,25.9,27.7,27.4,(CONTRACTS OF 100 TROY OUNCES),088691,CMX,88

## Net Positions

---

> Commercial (Long) = Producer/Merchant/Processor/User(Long) + Swap Dealers(Long) + Swap Dealers(Spreading)

> Commercial (Short) = Producer/Merchant/Processor/User(Short) + Swap Dealers(Short) + Swap Dealers(Spreading)

> Non-Commercial (Long) = Managed Money(Long) + Other Reportables(Long) 

> Non-Commercial (Short) = Managed Money(Short) + Other Reportables(Short) 

> Non-Commercial (Spreading) = Managed Money(Spreading) + Other Reportables(Spreading)

In [5]:
df['Commercial_Net_Position'] = df['Commercial Positions-Long (All)'] - df['Commercial Positions-Short (All)']
df['Large_Speculators_Net_Position'] = df['Noncommercial Positions-Long (All)'] - df['Noncommercial Positions-Short (All)']
df['Small_Traders_Net_Position'] = df['Nonreportable Positions-Long (All)'] - df['Nonreportable Positions-Short (All)']

df[['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position']].head()

,Commercial_Net_Position,Large_Speculators_Net_Position,Small_Traders_Net_Position
Date,,,
1986-01-15,-9028,10883,-1855
1986-01-31,-2988,6061,-3073
1986-02-14,18095,-6772,-11323
1986-02-28,17926,-4231,-13695
1986-03-14,7272,1622,-8894

## COT Index

The Commitments of Traders (COT) Index is calculated as:

$$
\text{COT Index} = \left( \frac{P_{\text{current}} - P_{\min}}{P_{\max} - P_{\min}} \right) \times 100
$$

Where:

$ P_{\text{current}} $: Current Net Position <br>
$ P_{\min} $: Lowest Net Position in the past  N  period <br>
$ P_{\max} $: Highest Net Position in the past  N  periods <br>
$ N $: Number of periods used in the lookback window


| Strategy                         | Recommended COT Index Period (N) | Notes                                                           |
| -------------------------------- | -------------------------------- | --------------------------------------------------------------- |
| **Swing Trading**                | **26 weeks** (6 months)          | Most popular. Balances short-term moves and sentiment extremes. |
| **Position Trading / Long-Term** | **52 weeks** (1 year)            | Captures major sentiment extremes and long-term reversals.      |
| **Short-Term Trading**           | **13 weeks** (3 months)          | More sensitive to recent changes, but can be noisy.             |
| **Contrarian Approach**          | Use 26–52 weeks                  | To spot positioning at sentiment extremes (close to 0 or 100).  |

In [6]:
window = 26 # Rolling window for the last N weeks

df['Max_Net_Position_Last_N'] = df['Commercial_Net_Position'].rolling(window=window).max()

df['Min_Net_Position_Last_N'] = df['Commercial_Net_Position'].rolling(window=window).min()

# df.dropna(inplace=True)

df['COT_Index'] = 100 * (df['Commercial_Net_Position'] - df['Min_Net_Position_Last_N'])/(df['Max_Net_Position_Last_N'] - df['Min_Net_Position_Last_N'])

df[['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position', 'COT_Index']].tail()

,Commercial_Net_Position,Large_Speculators_Net_Position,Small_Traders_Net_Position,COT_Index
Date,,,,
2025-06-17,-237727,200648,37079,65.821532
2025-06-24,-230560,195004,35556,71.037158
2025-07-01,-236069,201980,34089,67.028105
2025-07-08,-238354,202968,35386,65.365247
2025-07-15,-250688,213115,37573,56.389451

## Filter by time

In [7]:
df = df[['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position', 'COT_Index', 'Open Interest (All)']]
df = df.rename(columns={'Open Interest (All)': 'OI'})
df = df[df.index > '2020']

df.head()

,Commercial_Net_Position,Large_Speculators_Net_Position,Small_Traders_Net_Position,COT_Index,OI
Date,,,,,
2020-01-07,-356081,322291,33790,11.685731,785857
2020-01-14,-349819,319235,30584,21.197172,796883
2020-01-21,-351903,317695,34208,18.577760,793829
2020-01-28,-360814,330092,30722,7.258106,715539
2020-02-04,-331687,299806,31881,44.497290,654572

## Plotting

In [8]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

### COT index

In [9]:
fig = px.line(df.reset_index(), x='Date', y='COT_Index', title='COT index', markers=True, template='plotly_dark')

# Add green shaded area (e.g. for high index range)
fig.add_shape(
    type='rect',
    xref='paper',  # entire x-axis
    yref='y',
    x0=0,
    x1=1,
    y0=80,
    y1=100,
    fillcolor='green',
    opacity=0.2,
    line_width=0,
    layer='below'
)

# Add red shaded area (e.g. for low index range)
fig.add_shape(
    type='rect',
    xref='paper',
    yref='y',
    x0=0,
    x1=1,
    y0=0,
    y1=20,
    fillcolor='red',
    opacity=0.2,
    line_width=0,
    layer='below'
)

fig.write_html("plots/cot_index.html")

fig.show()

### Open Interest

In [10]:
fig = px.line(df.reset_index(), x='Date', y='OI', title='Open Interest', markers=True, template='plotly_dark')

fig.write_html("plots/open_interest.html")

fig.show()

### Net positions

In [11]:
fig = go.Figure()

for col in ['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position']:
    fig.add_trace(go.Scatter(x=df.index, y=df[col], mode='lines', name=col.replace('_Net_Position', '').replace('_', ' ').title(), line=dict(width=2)))

fig.update_layout(
        title='Net positions',
        xaxis_title='Date',
        yaxis_title='Contratcs',
        template='plotly_dark',
        height=600,
        width=1500,
    )

fig.write_html("plots/net_positions.html")
fig.show()

### Plotting all charts

In [12]:
# Create subplots: 1 column, 3 rows, shared X-axis
fig = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing= 0.1, subplot_titles=('COT Index', 'Net positions', 'OI'))

# Add each series to its own subplot
fig.add_trace(go.Scatter(x=df.index, y=df['COT_Index'], name='COT Index'), row=1, col=1)
for col in ['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position']:
    fig.add_trace(go.Scatter(x=df.index, y=df[col], name=col.replace('_Net_Position', '').replace('_', ' ').title(), line=dict(width=2)), row=2, col=1)
fig.add_trace(go.Scatter(x=df.index, y=df['OI'], name='OI'), row=3, col=1)

fig.add_shape(
    type='rect',
    xref='paper',  # spans the full width of the plot
    yref='y1',  # y-axis of subplot in row 1
    x0=0,
    x1=1,
    y0=80,       # Adjust based on your y-axis range
    y1=100,
    fillcolor='green',
    opacity=0.2,
    line_width=0,
    layer='below'
)

fig.add_shape(
    type='rect',
    xref='paper',  # spans the full width of the plot
    yref='y1',  # y-axis of subplot in row 1
    x0=0,
    x1=1,
    y0=0,              # Adjust based on your y-axis range
    y1=20,
    fillcolor='red',
    opacity=0.2,
    line_width=0,
    layer='below'
)


# Update layout
fig.update_layout(
    height=900,
    width=1450,
    title_text='Multiple Time Series with Shared X-Axis',
    template='plotly_dark',
    hovermode='x unified',  # or 'x unified' or 'closest',
)
fig.update_xaxes(title_text='Date', row=3, col=1)  # Only show x-axis label on bottom chart
fig.update_yaxes(title_text='CONTRACT')

# Save as responsive HTML
fig.write_html("plots/cot_analysis.html", auto_open=False, full_html=True, include_plotlyjs='cdn', config={'responsive': True})
fig.show()

## Asset chart

In [13]:
import yfinance as yf

ASSET_CHART_NAME = 'Gold Futures'

asset_price_df = yf.download("GC=F", start="2020-01-01", end="2025-07-23")

asset_price_df.columns = asset_price_df.columns.get_level_values(0)
asset_price_df.columns.name = None

asset_price_df.head()

/tmp/ipykernel_11468/883489983.py:5: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

                  Close         High          Low         Open  Volume
Date
2020-01-02  1524.500000  1528.699951  1518.000000  1518.099976     214
2020-01-03  1549.199951  1552.699951  1530.099976  1530.099976     107
2020-01-06  1566.199951  1580.000000  1560.400024  1580.000000     416
2020-01-07  1571.800049  1576.300049  1558.300049  1558.300049      47
2020-01-08  1557.400024  1604.199951  1552.300049  1579.699951     236

In [14]:
fig = go.Figure(data=[go.Candlestick(
    x=asset_price_df.index,
    open=asset_price_df['Open'],
    high=asset_price_df['High'],
    low=asset_price_df['Low'],
    close=asset_price_df['Close']
)])

fig.update_layout()

# Add zoom and pan tools explicitly
fig.update_layout(
    title=ASSET_CHART_NAME,
    xaxis_title='Date',
    yaxis_title='Price',
    width=1500,
    height=900,
    template='plotly_dark',
    # dragmode='zoom', 
    xaxis=dict(fixedrange=False, rangeslider=dict(visible=True)),
    yaxis=dict(fixedrange=False),
)

fig.show()

---

In [27]:
# Create subplots: 1 column, 3 rows, shared X-axis
fig = make_subplots(
    rows=4,
    cols=1,
    shared_xaxes=True,
    vertical_spacing= 0.07,
    row_heights=[0.55, 0.15, 0.15, 0.15],  # Increase height of first subplot
    subplot_titles=(f"ASSET_CHART_NAME (Daily)", 'COT Index', 'Net positions', 'OI')
)

# Add each series to its own subplot
fig.add_trace(go.Candlestick(
    x=asset_price_df.index,
    open=asset_price_df['Open'],
    high=asset_price_df['High'],
    low=asset_price_df['Low'],
    close=asset_price_df['Close']
), row=1, col=1)
fig.add_trace(go.Scatter(x=df.index, y=df['COT_Index'], name='COT Index'), row=2, col=1)

for col in ['Commercial_Net_Position', 'Large_Speculators_Net_Position', 'Small_Traders_Net_Position']:
    fig.add_trace(go.Scatter(x=df.index, y=df[col], name=col.replace('_Net_Position', '').replace('_', ' ').title(), line=dict(width=2)), row=3, col=1)

fig.add_trace(go.Scatter(x=df.index, y=df['OI'], name='OI'), row=4, col=1)

fig.add_shape(
    type='rect',
    xref='paper',  # spans the full width of the plot
    yref='y2',     # y-axis of subplot in row 2
    x0=0,
    x1=1,
    y0=80,         # Adjust based on COT Index range
    y1=100,
    fillcolor='green',
    opacity=0.2,
    line_width=0,
    layer='below'
)

fig.add_shape(
    type='rect',
    xref='paper',
    yref='y2',
    x0=0,
    x1=1,
    y0=0,
    y1=20,
    fillcolor='red',
    opacity=0.2,
    line_width=0,
    layer='below'
)


# Update layout
fig.update_layout(
    autosize=True,
    height=1200,
    width=1750,
    title_text=f"COT analysis {ASSET_CHART_NAME}",
    template='plotly_dark',
    xaxis_rangeslider_visible=False,
    hovermode='x unified',  # or 'x unified' or 'closest',

    spikedistance=-1,
    xaxis=dict(showspikes=True, spikemode='across', spikesnap='cursor', showline=True),
    xaxis2=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
    xaxis3=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
    xaxis4=dict(showspikes=True, spikemode='across', spikesnap='cursor'),

    yaxis=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
    yaxis2=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
    yaxis3=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
    yaxis4=dict(showspikes=True, spikemode='across', spikesnap='cursor'),
)

# Only show x-axis label on bottom chart
fig.update_xaxes(title_text='Date', row=4, col=1)

# Optional: Customize y-axis titles per row if needed
fig.update_yaxes(title_text='Price', row=1, col=1)
fig.update_yaxes(title_text='%', row=2, col=1)
fig.update_yaxes(title_text='CONTRACT', row=3, col=1)
fig.update_yaxes(title_text='CONTRACT', row=4, col=1)

# Save as responsive HTML
fig.write_html(f"plots/{ASSET_CHART_NAME.replace(' ', '_').lower()}_cot_analysis.html", auto_open=False, full_html=True, include_plotlyjs='cdn', config={'responsive': True})
fig.show()