In [2]:
import pandas as pd
from analysis import get_market_participants
from utils import get_market_df, TRADERS_IN_FINANCIAL_FUTURES_FUT, LEGUACY_FUT, DISAGGREGATED_FUT, print_json

In [3]:
N = 26

MARKET = "AUSTRALIAN DOLLAR"
REPORT_TYPE = LEGUACY_FUT

In [4]:
df = get_market_df(cot_report_type=REPORT_TYPE, market=MARKET)

loading data for the report type: legacy_fut ...
Selected: Legacy Report Futures-only - loading historical data ...
Selected: Legacy Report Futures-only from year: 2017 - loading data ...
Selected: Legacy Report Futures-only from year: 2018 - loading data ...
Selected: Legacy Report Futures-only from year: 2019 - loading data ...
Selected: Legacy Report Futures-only from year: 2020 - loading data ...
Selected: Legacy Report Futures-only from year: 2021 - loading data ...
Selected: Legacy Report Futures-only from year: 2022 - loading data ...
Selected: Legacy Report Futures-only from year: 2023 - loading data ...
Selected: Legacy Report Futures-only from year: 2024 - loading data ...
Selected: Legacy Report Futures-only from year: 2025 - loading data ...
Selected: Legacy Report Futures-only from year: 2026 - loading data ...

In [5]:
df.tail()

,market_and_exchange_names,as_of_date_in_form_yymmdd,cftc_contract_market_code,cftc_market_code_in_initials,cftc_region_code,cftc_commodity_code,open_interest_all,noncommercial_positions_long_all,noncommercial_positions_short_all,noncommercial_positions_spreading_all,...,concentration_gross_lt_=8_tdr_long_other,concentration_gross_lt_=8_tdr_shortother,concentration_net_lt_=4_tdr_long_other,concentration_net_lt_=4_tdr_short_other,concentration_net_lt_=8_tdr_long_other,concentration_net_lt_=8_tdr_short_other,contract_units,cftc_contract_market_code_quotes,cftc_market_code_in_initials_quotes,cftc_commodity_code_quotes
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-10,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,260210,232741,CME,0,232,247194,112766,79557,3749,...,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF AUD 100,000)",232741,CME,232
2026-02-17,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,260217,232741,CME,0,232,256213,117820,71889,9938,...,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF AUD 100,000)",232741,CME,232
2026-02-24,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,260224,232741,CME,0,232,248697,121661,69017,9052,...,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF AUD 100,000)",232741,CME,232
2026-03-03,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,260303,232741,CME,0,232,267280,136515,68753,17223,...,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF AUD 100,000)",232741,CME,232
2026-03-10,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,260310,232741,CME,0,232,315898,121394,67197,24105,...,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF AUD 100,000)",232741,CME,232

In [6]:
participants = get_market_participants(df)

list(participants.keys())

['noncommercial', 'commercial', 'total_reportable', 'nonreportable']

In [7]:
participant_STR = 'noncommercial'

picked_participant = participants[participant_STR]

print_json(picked_participant)

{
        "oi_all": "open_interest_all",
        "long": "noncommercial_positions_long_all",
        "short": "noncommercial_positions_short_all",
        "spread": "noncommercial_positions_spreading_all",
        "long_oi": "%_of_oi_noncommercial_long_all",
        "short_oi": "%_of_oi_noncommercial_short_all",
        "spread_oi": "%_of_oi_noncommercial_spreading_all",
        "long_change": "change_in_noncommercial_long_all",
        "short_change": "change_in_noncommercial_short_all",
        "spread_change": "change_in_noncommercial_spreading_all"
}

In [8]:
change_col = lambda side: f"{side}_change"
oi_col = lambda side: f"oi_{side}(%)"

In [9]:
picked_participant_df = pd.DataFrame({})

for side in ['long', 'short',  'spread']:
    if side not in picked_participant: continue
    picked_participant_df[side] = df[picked_participant[side]]
    picked_participant_df[change_col(side)] = pd.to_numeric(df[picked_participant[f'{side}_change']], errors="coerce")
    picked_participant_df[oi_col(side)] = df[picked_participant[f"{side}_oi"]]

picked_participant_df['oi_all'] = df[picked_participant["oi_all"]]

picked_participant_df['net'] = picked_participant_df['long'] - picked_participant_df['short']
picked_participant_df['net_change(%)'] = 100 * picked_participant_df['net'].pct_change(periods=1)
picked_participant_df['net/oi_all(%)'] = 100*picked_participant_df['net']/df[picked_participant["oi_all"]]

picked_participant_df['total'] = (
    picked_participant_df['long'] +
    picked_participant_df['short'] +
    (picked_participant_df['spread'] if 'spread' in picked_participant_df else 0)
)

picked_participant_df['long(%)'] = 100 * picked_participant_df['long'] / picked_participant_df['total']
picked_participant_df['short(%)'] = 100 * picked_participant_df['short'] / picked_participant_df['total']
if 'spread' in picked_participant_df:
    picked_participant_df['spread(%)'] = 100 * picked_participant_df['spread'] / picked_participant_df['total']

picked_participant_df['net/total(%)'] = 100 * picked_participant_df['net']/picked_participant_df['total']

- **Stats**

In [10]:
# summary = picked_participant_df.tail(N*2).describe().loc[['min', 'max', 'mean']]
summary = picked_participant_df.tail(N*2).agg(['min', 'max', 'mean'])

for col in summary.select_dtypes(include="number").columns:
    summary[col] = summary[col].apply(lambda x: float(f"{x:.10g}"))

In [11]:
color_map = {
    "long": "Greens",
    "short": "Reds",
    "spread": "Blues",
    "net": "RdYlGn",
    "amalgamated": "Greys"
}
# https://matplotlib.org/stable/users/explain/colors/colormaps.html

picked_participant_df = picked_participant_df.tail(N)

styled = picked_participant_df.style

for side in ["long", "short", "spread"]:
    if side not in picked_participant: continue
    (
      styled
            .background_gradient(cmap=color_map[side], subset=[side], vmin=picked_participant_df[side].min(), vmax=picked_participant_df[side].max())
            .background_gradient(cmap=color_map[side], subset=[change_col(side)], vmin=picked_participant_df[change_col(side)].min(), vmax=picked_participant_df[change_col(side)].max())
            # .background_gradient(cmap=color_map[side], subset=[oi_col(side)], vmin=picked_participant_df[oi_col(side)].min(), vmax=picked_participant_df[oi_col(side)].max())
    )

(
    styled
        .bar(subset=["oi_long(%)"], color='#41ab5d', vmin=0, vmax=100)
        .bar(subset=["oi_short(%)"], color='#ef3b2c', vmin=0, vmax=100)
)

(
    styled
        .background_gradient(cmap=color_map['net'], subset=['net'], vmin=picked_participant_df['net'].min(), vmax=picked_participant_df['net'].max())
        .background_gradient(cmap=color_map['net'], subset=['net/oi_all(%)'], vmin=picked_participant_df['net/oi_all(%)'].min(), vmax=picked_participant_df['net/oi_all(%)'].max())
        .background_gradient(cmap=color_map['net'], subset=['net/total(%)'], vmin=picked_participant_df['net/total(%)'].min(), vmax=picked_participant_df['net/total(%)'].max())
        .background_gradient(cmap=color_map['net'], subset=['net_change(%)'], vmin=picked_participant_df['net_change(%)'].min(), vmax=picked_participant_df['net_change(%)'].max())
        .background_gradient(cmap=color_map['amalgamated'], subset=["total"], vmin=picked_participant_df["total"].min(), vmax=picked_participant_df["total"].max())
        # .background_gradient(cmap=color_map['long'], subset=["long(%)"], vmin=picked_participant_df["long(%)"].min(), vmax=picked_participant_df["long(%)"].max())
        # .background_gradient(cmap=color_map['short'], subset=["short(%)"], vmin=picked_participant_df["short(%)"].min(), vmax=picked_participant_df["short(%)"].max())
        .bar(subset=["long(%)"], color="#41ab5d", vmin=0, vmax=100)
        .bar(subset=["short(%)"], color='#ef3b2c', vmin=0, vmax=100)
        .background_gradient(cmap=color_map['amalgamated'], subset=["oi_all"], vmin=picked_participant_df["oi_all"].min(), vmax=picked_participant_df["oi_all"].max())
)

if 'spread' in picked_participant:
    (
    styled
        .bar(subset=["spread(%)"], color='#4292c6', vmin=0, vmax=100)
        .bar(subset=["oi_spread(%)"], color='#4292c6', vmin=0, vmax=100)
    )
    # styled.background_gradient(cmap=color_map['spread'], subset=["spread(%)"], vmin=picked_participant_df["spread(%)"].min(), vmax=picked_participant_df["spread(%)"].max())

styled.format("{:g}")
# styled.format({"long": "{:,.0f}","oi_long(%)": "{:.1f}%"})
styled.format_index("{:%Y-%m-%d}", axis=0)

styled.set_table_styles([
        {
            "selector": "tbody tr",
            "props": [("border-bottom", "2px solid gray")]
        },
        {
            "selector": "td",
            "props": [("border-right", "2px solid gray")]
        }
    ])

styled

In [12]:
summary = summary.map(lambda x: float(f'{x:g}') if isinstance(x, float) else x)

summary

,long,long_change,oi_long(%),short,short_change,oi_short(%),spread,spread_change,oi_spread(%),oi_all,net,net_change(%),net/oi_all(%),total,long(%),short(%),spread(%),net/total(%)
min,19740.0,-24543.00,10.7000,67197.0,-30981.000,21.3000,1416.00,-15285.000,0.60000,147471.0,-100590.0,-151.00300,-52.6079,111709.0,16.9139,30.9015,0.69388,-61.3354
max,136515.0,24047.00,51.1000,129290.0,13019.000,68.1000,24584.00,15012.000,12.10000,315898.0,67762.0,265.49100,25.3524,222491.0,61.3575,78.8354,18.11950,30.4561
mean,49441.8,1331.21,23.5577,98855.6,-638.462,52.1519,8070.15,251.846,4.09231,197900.0,-49413.8,3.04246,-28.5879,156368.0,29.4308,65.0074,5.56180,-35.5767

In [13]:
# styled.to_html("styled_table.html")

### Prompt

In [14]:
content = f"""
                Here is a COT snapshot of the {participant_STR} market participant in the {MARKET} market for the last {N} reports:
                {picked_participant_df.to_json()}

                net = long - short
                total = long + short + spread
                spread = long and short positions held by the same trader
                oi_all = open interest of the market participant

                make a very short and concise market positioning analysis based on the above data.
                summarize the trend in one clear sentence about potential price direction
                don't make more than 5 sentences in total.
            """

print(content)

                Here is a COT snapshot of the noncommercial market participant in the AUSTRALIAN DOLLAR market for the last 26 reports:
                {"long":{"1757980800000":40276,"1758585600000":41994,"1759190400000":41713,"1759795200000":47717,"1760400000000":50324,"1761004800000":51794,"1761609600000":41715,"1762214400000":50360,"1762732800000":43114,"1763424000000":45721,"1764028800000":43918,"1764633600000":45868,"1765238400000":57569,"1765843200000":67640,"1766448000000":70657,"1767052800000":77497,"1767657600000":80491,"1768262400000":83955,"1768867200000":85759,"1769472000000":109806,"1770076800000":118751,"1770681600000":112766,"1771286400000":117820,"1771891200000":121661,"1772496000000":136515,"1773100800000":121394},"long_change":{"1757980800000":8076.0,"1758585600000":1718.0,"1759190400000":-281.0,"1759795200000":6004.0,"1760400000000":2607.0,"1761004800000":1470.0,"1761609600000":-10079.0,"1762214400000":8645.0,"1762732800000":-7246.0,"1763424000000":2607.0,"1764028800000":-1803.0,"1764633600000":1950.0,"1765238400000":11701.0,"1765843200000":10071.0,"1766448000000":3017.0,"1767052800000":6840.0,"1767657600000":2994.0,"1768262400000":3464.0,"1768867200000":1804.0,"1769472000000":24047.0,"1770076800000":8945.0,"1770681600000":-5985.0,"1771286400000":5054.0,"1771891200000":3841.0,"1772496000000":14854.0,"1773100800000":-15121.0},"oi_long(%)":{"1757980800000":26.0,"1758585600000":26.1,"1759190400000":24.8,"1759795200000":27.9,"1760400000000":29.6,"1761004800000":29.8,"1761609600000":24.1,"1762214400000":27.9,"1762732800000":24.0,"1763424000000":25.5,"1764028800000":22.8,"1764633600000":22.6,"1765238400000":19.4,"1765843200000":23.0,"1766448000000":32.5,"1767052800000":34.6,"1767657600000":34.9,"1768262400000":36.6,"1768867200000":37.2,"1769472000000":43.6,"1770076800000":46.7,"1770681600000":45.6,"1771286400000":46.0,"1771891200000":48.9,"1772496000000":51.1,"1773100800000":38.4},"short":{"1757980800000":91436,"1758585600000":101584,"1759190400000":106319,"1759795200000":105522,"1760400000000":109902,"1761004800000":117558,"1761609600000":115649,"1762214400000":121936,"1762732800000":121741,"1763424000000":121577,"1764028800000":128094,"1764633600000":129261,"1765238400000":120516,"1765843200000":89535,"1766448000000":92255,"1767052800000":98713,"1767657600000":99451,"1768262400000":102801,"1768867200000":99770,"1769472000000":102660,"1770076800000":92633,"1770681600000":79557,"1771286400000":71889,"1771891200000":69017,"1772496000000":68753,"1773100800000":67197},"short_change":{"1757980800000":-19995.0,"1758585600000":10148.0,"1759190400000":4735.0,"1759795200000":-797.0,"1760400000000":4380.0,"1761004800000":7656.0,"1761609600000":-1909.0,"1762214400000":6287.0,"1762732800000":-195.0,"1763424000000":-164.0,"1764028800000":6517.0,"1764633600000":1167.0,"1765238400000":-8745.0,"1765843200000":-30981.0,"1766448000000":2720.0,"1767052800000":6458.0,"1767657600000":738.0,"1768262400000":3350.0,"1768867200000":-3031.0,"1769472000000":2890.0,"1770076800000":-10027.0,"1770681600000":-13076.0,"1771286400000":-7668.0,"1771891200000":-2872.0,"1772496000000":-264.0,"1773100800000":-1556.0},"oi_short(%)":{"1757980800000":59.1,"1758585600000":63.2,"1759190400000":63.3,"1759795200000":61.7,"1760400000000":64.6,"1761004800000":67.6,"1761609600000":66.7,"1762214400000":67.4,"1762732800000":67.8,"1763424000000":67.8,"1764028800000":66.5,"1764633600000":63.8,"1765238400000":40.6,"1765843200000":30.5,"1766448000000":42.5,"1767052800000":44.1,"1767657600000":43.1,"1768262400000":44.8,"1768867200000":43.3,"1769472000000":40.7,"1770076800000":36.4,"1770681600000":32.2,"1771286400000":28.1,"1771891200000":27.8,"1772496000000":25.7,"1773100800000":21.3},"spread":{"1757980800000":2519,"1758585600000":1590,"1759190400000":1643,"1759795200000":1416,"1760400000000":3241,"1761004800000":1868,"1761609600000":2820,"1762214400000":1784,"1762732800000":3260,"1763424000000":1567,"1764028800000":5734,"1764633600000":5144,"1765238400000":20156,"1765843200000":4871,"1766448000000":3370,"1767052800000":2991,"1767657600000":4780,"1768262400000":2416,"1768867200000":1592,"1769472000000":1593,"1770076800000":1477,"1770681600000":3749,"1771286400000":9938,"1771891200000":9052,"1772496000000":17223,"1773100800000":24105},"spread_change":{"1757980800000":-7193.0,"1758585600000":-929.0,"1759190400000":53.0,"1759795200000":-227.0,"1760400000000":1825.0,"1761004800000":-1373.0,"1761609600000":952.0,"1762214400000":-1036.0,"1762732800000":1476.0,"1763424000000":-1693.0,"1764028800000":4167.0,"1764633600000":-590.0,"1765238400000":15012.0,"1765843200000":-15285.0,"1766448000000":-1501.0,"1767052800000":-379.0,"1767657600000":1789.0,"1768262400000":-2364.0,"1768867200000":-824.0,"1769472000000":1.0,"1770076800000":-116.0,"1770681600000":2272.0,"1771286400000":6189.0,"1771891200000":-886.0,"1772496000000":8171.0,"1773100800000":6882.0},"oi_spread(%)":{"1757980800000":1.6,"1758585600000":1.0,"1759190400000":1.0,"1759795200000":0.8,"1760400000000":1.9,"1761004800000":1.1,"1761609600000":1.6,"1762214400000":1.0,"1762732800000":1.8,"1763424000000":0.9,"1764028800000":3.0,"1764633600000":2.5,"1765238400000":6.8,"1765843200000":1.7,"1766448000000":1.6,"1767052800000":1.3,"1767657600000":2.1,"1768262400000":1.1,"1768867200000":0.7,"1769472000000":0.6,"1770076800000":0.6,"1770681600000":1.5,"1771286400000":3.9,"1771891200000":3.6,"1772496000000":6.4,"1773100800000":7.6},"oi_all":{"1757980800000":154790,"1758585600000":160854,"1759190400000":167976,"1759795200000":170970,"1760400000000":170002,"1761004800000":173878,"1761609600000":173436,"1762214400000":180801,"1762732800000":179467,"1763424000000":179341,"1764028800000":192678,"1764633600000":202574,"1765238400000":296662,"1765843200000":293796,"1766448000000":217163,"1767052800000":223804,"1767657600000":230926,"1768262400000":229456,"1768867200000":230657,"1769472000000":252055,"1770076800000":254240,"1770681600000":247194,"1771286400000":256213,"1771891200000":248697,"1772496000000":267280,"1773100800000":315898},"net":{"1757980800000":-51160,"1758585600000":-59590,"1759190400000":-64606,"1759795200000":-57805,"1760400000000":-59578,"1761004800000":-65764,"1761609600000":-73934,"1762214400000":-71576,"1762732800000":-78627,"1763424000000":-75856,"1764028800000":-84176,"1764633600000":-83393,"1765238400000":-62947,"1765843200000":-21895,"1766448000000":-21598,"1767052800000":-21216,"1767657600000":-18960,"1768262400000":-18846,"1768867200000":-14011,"1769472000000":7146,"1770076800000":26118,"1770681600000":33209,"1771286400000":45931,"1771891200000":52644,"1772496000000":67762,"1773100800000":54197},"net_change(%)":{"1757980800000":-35.4293142836,"1758585600000":16.4777169664,"1759190400000":8.4175197181,"1759795200000":-10.5268860477,"1760400000000":3.067208719,"1761004800000":10.383027292,"1761609600000":12.423210267,"1762214400000":-3.189331025,"1762732800000":9.8510673969,"1763424000000":-3.5242346777,"1764028800000":10.9681501793,"1764633600000":-0.9301938795,"1765238400000":-24.5176453659,"1765843200000":-65.2167696634,"1766448000000":-1.3564740808,"1767052800000":-1.7686822854,"1767657600000":-10.6334841629,"1768262400000":-0.6012658228,"1768867200000":-25.6553114719,"1769472000000":-151.0027835272,"1770076800000":265.4911838791,"1770681600000":27.1498583352,"1771286400000":38.3088921678,"1771891200000":14.6154013629,"1772496000000":28.7174226882,"1773100800000":-20.0185944925},"net\/oi_all(%)":{"1757980800000":-33.0512306997,"1758585600000":-37.0460168849,"1759190400000":-38.4614468734,"1759795200000":-33.8100251506,"1760400000000":-35.0454700533,"1761004800000":-37.8219211171,"1761609600000":-42.6289812957,"1762214400000":-39.5882766135,"1762732800000":-43.8113970814,"1763424000000":-42.297076519,"1764028800000":-43.6873955511,"1764633600000":-41.166684767,"1765238400000":-21.2184236606,"1765843200000":-7.4524499993,"1766448000000":-9.9455247901,"1767052800000":-9.4797233293,"1767657600000":-8.2104223864,"1768262400000":-8.2133393766,"1768867200000":-6.0743875105,"1769472000000":2.8350955149,"1770076800000":10.2729704216,"1770681600000":13.434387566,"1771286400000":17.9268811497,"1771891200000":21.1679272368,"1772496000000":25.3524393894,"1773100800000":17.1564872206},"total":{"1757980800000":134231,"1758585600000":145168,"1759190400000":149675,"1759795200000":154655,"1760400000000":163467,"1761004800000":171220,"1761609600000":160184,"1762214400000":174080,"1762732800000":168115,"1763424000000":168865,"1764028800000":177746,"1764633600000":180273,"1765238400000":198241,"1765843200000":162046,"1766448000000":166282,"1767052800000":179201,"1767657600000":184722,"1768262400000":189172,"1768867200000":187121,"1769472000000":214059,"1770076800000":212861,"1770681600000":196072,"1771286400000":199647,"1771891200000":199730,"1772496000000":222491,"1773100800000":212696},"long(%)":{"1757980800000":30.0049913954,"1758585600000":28.9278628899,"1759190400000":27.8690496075,"1759795200000":30.8538359575,"1760400000000":30.7854184637,"1761004800000":30.2499707978,"1761609600000":26.0419267842,"1762214400000":28.9292279412,"1762732800000":25.6455402552,"1763424000000":27.0754744915,"1764028800000":24.7082916071,"1764633600000":25.4436327126,"1765238400000":29.039905973,"1765843200000":41.7412339706,"1766448000000":42.4922721642,"1767052800000":43.2458524227,"1767657600000":43.574127608,"1768262400000":44.3802465481,"1768867200000":45.8307726017,"1769472000000":51.2970723025,"1770076800000":55.7880494783,"1770681600000":57.5125464115,"1771286400000":59.0141599924,"1771891200000":60.9127321885,"1772496000000":61.3575380577,"1773100800000":57.0739459134},"short(%)":{"1757980800000":68.1183929197,"1758585600000":69.9768544032,"1759190400000":71.0332386838,"1759795200000":68.2305777375,"1760400000000":67.2319183688,"1761004800000":68.6590351594,"1761609600000":72.1975977626,"1762214400000":70.0459558824,"1762732800000":72.4153109479,"1763424000000":71.9965653036,"1764028800000":72.065756754,"1764633600000":71.7029172422,"1765238400000":60.7926715462,"1765843200000":55.2528294435,"1766448000000":55.481050264,"1767052800000":55.0850720699,"1767657600000":53.8382001061,"1768262400000":54.3426088427,"1768867200000":53.3184410088,"1769472000000":47.9587403473,"1770076800000":43.5180704779,"1770681600000":40.5754008731,"1771286400000":36.0080542157,"1771891200000":34.5551494518,"1772496000000":30.9014746664,"1773100800000":31.5929777711},"spread(%)":{"1757980800000":1.8766156849,"1758585600000":1.0952827069,"1759190400000":1.0977117087,"1759795200000":0.915586305,"1760400000000":1.9826631675,"1761004800000":1.0909940428,"1761609600000":1.7604754532,"1762214400000":1.0248161765,"1762732800000":1.939148797,"1763424000000":0.9279602049,"1764028800000":3.2259516389,"1764633600000":2.8534500452,"1765238400000":10.1674224807,"1765843200000":3.0059365859,"1766448000000":2.0266775718,"1767052800000":1.6690755074,"1767657600000":2.5876722859,"1768262400000":1.2771446091,"1768867200000":0.8507863896,"1769472000000":0.7441873502,"1770076800000":0.6938800438,"1770681600000":1.9120527153,"1771286400000":4.9777857919,"1771891200000":4.5321183598,"1772496000000":7.7409872759,"1773100800000":11.3330763155},"net\/total(%)":{"1757980800000":-38.1134015242,"1758585600000":-41.0489915133,"1759190400000":-43.1641890763,"1759795200000":-37.3767417801,"1760400000000":-36.4464999052,"1761004800000":-38.4090643616,"1761609600000":-46.1556709784,"1762214400000":-41.1167279412,"1762732800000":-46.7697706927,"1763424000000":-44.9210908122,"1764028800000":-47.3574651469,"1764633600000":-46.2592845296,"1765238400000":-31.7527655732,"1765843200000":-13.5115954729,"1766448000000":-12.9887780999,"1767052800000":-11.8392196472,"1767657600000":-10.2640724981,"1768262400000":-9.9623622946,"1768867200000":-7.4876684071,"1769472000000":3.3383319552,"1770076800000":12.2699790004,"1770681600000":16.9371455384,"1771286400000":23.0061057767,"1771891200000":26.3575827367,"1772496000000":30.4560633913,"1773100800000":25.4809681423}}

                net = long - short
                total = long + short + spread
                spread = long and short positions held by the same trader
                oi_all = open interest of the market participant

                make a very short and concise market positioning analysis based on the above data.
                summarize the trend in one clear sentence about potential price direction
                don't make more than 5 sentences in total.

In [15]:
# from openai import OpenAI

# client = OpenAI(api_key="sk-...")

# response = client.chat.completions.create(
#     model="gpt-4o-mini",
#     messages=[
#         {
#             "role": "system",
#             "content": "You are a market positioning analyst. Respond with ONE short phrase only."
#         },
#         {
#             "role": "user",
#             "content": content
#         }
#     ],
#     temperature=0
# )

# print(response.choices[0].message.content)

### **Percentage of participant positions**

In [16]:
import plotly.graph_objects as go

pie_df = picked_participant_df.tail(1)[[
    "long(%)", "short(%)", "spread(%)"
]]

labels = pie_df.columns.tolist()
values = pie_df.iloc[0].tolist()

fig = go.Figure(
    data=[go.Pie(labels=labels, values=values)]
)

fig.update_layout(
    height=700,
    width=700,
    template='plotly_dark',
    legend=dict(font=dict(size=16)),
    title=dict(text=f"Percentage of {participant_STR} positions", font=dict(size=24)),
)

fig.show()